import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Proposal, Lead, ProposalOption, MasterHotel, MasterActivity } from '../types';

export const generateProposalPDF = (proposal: Proposal, lead: Lead, masterHotels: MasterHotel[] = [], masterActivities: MasterActivity[] = []) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // --- Header ---
    doc.setFillColor(88, 28, 135); // Purple-900 (approx)
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("SHRAWELLO TRAVEL HUB", 15, 25);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Making Dreams Come True", 15, 32);

    doc.text("Proposal", pageWidth - 15, 20, { align: 'right' });
    doc.setFontSize(12);
    doc.text(`#${proposal.id}`, pageWidth - 15, 28, { align: 'right' });

    // --- Customer Info ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    let yPos = 55;

    doc.setFont("helvetica", "bold");
    doc.text("Prepared For:", 15, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(lead.name, 15, yPos + 5);
    doc.text(lead.email || '', 15, yPos + 10);
    doc.text(lead.phone || '', 15, yPos + 15);

    doc.setFont("helvetica", "bold");
    doc.text("Destination:", pageWidth / 2, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(lead.destination || 'Custom', pageWidth / 2, yPos + 5);

    doc.setFont("helvetica", "bold");
    doc.text("Valid Date:", pageWidth - 50, yPos);
    doc.setFont("helvetica", "normal");
    const validUntil = proposal.validUntil ? new Date(proposal.validUntil).toLocaleDateString() : '7 Days from issue';
    doc.text(validUntil, pageWidth - 50, yPos + 5);

    yPos += 30;

    // --- Proposal Title ---
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(proposal.title, 15, yPos);
    yPos += 5;

    // --- Options ---
    proposal.options.forEach((option, index) => {
        if (yPos > 240) {
            doc.addPage();
            yPos = 20;
        }

        yPos += 15;

        // Option Header
        doc.setFillColor(243, 244, 246); // Gray-100
        doc.roundedRect(15, yPos, pageWidth - 30, 20, 3, 3, 'F');

        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(88, 28, 135); // Purple
        doc.text(option.name, 20, yPos + 13);

        doc.setTextColor(0, 0, 0);
        doc.text(`₹${option.price.toLocaleString()}`, pageWidth - 25, yPos + 13, { align: 'right' });

        yPos += 25;

        // --- Content Resolution ---
        // Resolve Hotels
        const hotelNames = option.hotels.map(hId => {
            const h = masterHotels.find(mh => mh.id === hId);
            return h ? `${h.name} (${h.rating} Star)` : hId;
        });

        // Resolve Activities
        const activityNames = (option.activities || []).map(aId => {
            const a = masterActivities.find(ma => ma.id === aId);
            return a ? a.name : aId;
        });

        // Inclusions List
        const inclusions = [...option.inclusions];

        // Format Body for AutoTable
        const bodyRows: string[][] = [];

        if (hotelNames.length > 0) {
            bodyRows.push(['Hotels', hotelNames.join('\n')]);
        }
        if (activityNames.length > 0) {
            bodyRows.push(['Services/Activities', activityNames.join('\n')]);
        }
        if (inclusions.length > 0) {
            bodyRows.push(['Inclusions', inclusions.map(i => `• ${i}`).join('\n')]);
        }

        // Using autoTable for cleaner list
        autoTable(doc, {
            startY: yPos,
            margin: { left: 15, right: 15 },
            head: [],
            body: bodyRows,
            theme: 'grid',
            styles: { fontSize: 10, cellPadding: 4, valign: 'top' },
            columnStyles: {
                0: { cellWidth: 40, fontStyle: 'bold', textColor: [88, 28, 135] },
                1: { cellWidth: 'auto' }
            },
        });

        // @ts-ignore
        yPos = doc.lastAutoTable.finalY + 5;
    });

    // --- Footer ---
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
        doc.text(`Generated by SHRAWELLO Travel Hub`, 15, doc.internal.pageSize.height - 10);
    }

    doc.save(`Quotation_${lead.name.replace(/\s+/g, '_')}_${proposal.id}.pdf`);
};

export const generateProformaInvoice = (proposal: Proposal, optionId: string, lead: Lead) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const option = proposal.options.find(o => o.id === optionId);

    if (!option) return;

    // --- Company Data ---
    const company = {
        name: "SHRAWELLO TRAVEL HUB",
        addressLine1: "A508, Wisteria, Patil Nagar,",
        addressLine2: "Chikhali, PCMC, Pune, MH - 411062",
        phone: "+91 80109 55675",
        email: "shravyatours23@gmail.com",
        gstin: "27BKSPK0858C1Z6", // Updated Validation
        bank: {
            name: "HDFC Bank",
            accountName: "SHRAWELLO TRAVEL HUB",
            accountNo: "50200088927878",
            ifsc: "HDFC0000007",
            branch: "Pune - Chikhali"
        }
    };

    // --- Calculations (Assuming 5% GST Inclusive) ---
    const gstRate = 5;
    const totalPrice = option.price;
    const taxableValue = totalPrice / (1 + gstRate / 100);
    const gstAmount = totalPrice - taxableValue;
    const cgst = gstAmount / 2;
    const sgst = gstAmount / 2;

    // --- Header ---
    doc.setFillColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("PROFORMA INVOICE", pageWidth - 15, 25, { align: 'right' });

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 15, 33, { align: 'right' });
    doc.text(`Ref No: PI-${proposal.id.slice(-6).toUpperCase()}`, pageWidth - 15, 38, { align: 'right' });

    // Logo Placeholder or Text
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(88, 28, 135);
    doc.text(company.name, 15, 25);

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(company.addressLine1, 15, 32);
    doc.text(company.addressLine2, 15, 36);
    doc.text(`Phone: ${company.phone}`, 15, 40);
    doc.text(`Email: ${company.email}`, 15, 44);
    doc.text(`GSTIN: ${company.gstin}`, 15, 48);

    doc.setDrawColor(200, 200, 200);
    doc.line(15, 55, pageWidth - 15, 55);

    // Bill To
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Bill To:", 15, 65);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(lead.name, 15, 71);
    if (lead.email) doc.text(lead.email, 15, 76);
    if (lead.phone) doc.text(lead.phone, 15, 81);
    doc.text(`Place of Supply: ${lead.location || 'State Code 00'}`, 15, 86);

    // --- Table ---
    autoTable(doc, {
        startY: 95,
        head: [['S.No', 'Description', 'HSN/SAC', 'Taxable Val', 'CGST (2.5%)', 'SGST (2.5%)', 'Total']],
        body: [[
            '1',
            `Tour Package: ${proposal.title}\nOption: ${option.name}`,
            '9985', // Tour Operator Service
            taxableValue.toFixed(2),
            cgst.toFixed(2),
            sgst.toFixed(2),
            totalPrice.toLocaleString('en-IN')
        ]],
        foot: [[
            '', 'Total', '', taxableValue.toFixed(2), cgst.toFixed(2), sgst.toFixed(2), `INR ${totalPrice.toLocaleString('en-IN')}`
        ]],
        theme: 'grid',
        headStyles: { fillColor: [88, 28, 135], textColor: 255, halign: 'center' },
        bodyStyles: { valign: 'middle', halign: 'center' },
        footStyles: { fillColor: [243, 244, 246], textColor: 0, fontStyle: 'bold', halign: 'center' },
        columnStyles: {
            1: { halign: 'left', cellWidth: 60 }
        }
    });

    // --- Bank Details ---
    // @ts-ignore
    let yPos = doc.lastAutoTable.finalY + 15;

    doc.setFillColor(243, 244, 246);
    doc.roundedRect(15, yPos, pageWidth / 2, 45, 3, 3, 'F');

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Bank Details:", 20, yPos + 8);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    yPos += 14;
    doc.text(`Account Name: ${company.bank.accountName}`, 20, yPos);
    doc.text(`Bank Name: ${company.bank.name}`, 20, yPos + 5);
    doc.text(`Account Number: ${company.bank.accountNo}`, 20, yPos + 10);
    doc.text(`IFSC Code: ${company.bank.ifsc}`, 20, yPos + 15);
    doc.text(`Branch: ${company.bank.branch}`, 20, yPos + 20);

    // --- Terms ---
    // @ts-ignore
    yPos = doc.lastAutoTable.finalY + 15;
    const termsX = pageWidth / 2 + 20;

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Terms & Conditions:", termsX, yPos + 8);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text("1. This is a computer generated invoice.", termsX, yPos + 14);
    doc.text("2. 100% Advance payment required.", termsX, yPos + 19);
    doc.text("3. Non-refundable as per policy.", termsX, yPos + 24);

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Thank you for choosing SHRAWELLO Travel Hub!", pageWidth / 2, pageHeight - 15, { align: 'center' });

    doc.save(`Proforma_${lead.name.replace(/\s+/g, '_')}_${proposal.id}.pdf`);
};

export const generateBookingInvoice = (booking: any, customer: any) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // --- Mock Company Data ---
    const company = {
        name: "SHRAWELLO TRAVEL HUB",
        addressLine1: "A508, Wisteria, Patil Nagar,",
        addressLine2: "Chikhali, PCMC, Pune, MH - 411062",
        phone: "+91 80109 55675",
        email: "shravyatours23@gmail.com",
        gstin: "27BKSPK0858C1Z6",
        bank: {
            name: "HDFC Bank",
            accountName: "SHRAWELLO TRAVEL HUB",
            accountNo: "50200088927878",
            ifsc: "HDFC0000007",
            branch: "Pune - Chikhali"
        }
    };

    // --- Header ---
    doc.setFillColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("INVOICE", pageWidth - 15, 25, { align: 'right' });

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Invoice No: ${booking.invoiceNo || 'DRAFT'}`, pageWidth - 15, 33, { align: 'right' });
    doc.text(`Date: ${new Date(booking.date).toLocaleDateString()}`, pageWidth - 15, 38, { align: 'right' });

    // Company Info
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(company.name, 15, 25);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(company.addressLine1, 15, 32);
    doc.text(company.addressLine2, 15, 36);
    doc.text(`Phone: ${company.phone}`, 15, 40);
    doc.text(`Email: ${company.email}`, 15, 44);
    doc.text(`GSTIN: ${company.gstin}`, 15, 48);

    doc.line(15, 55, pageWidth - 15, 55);

    // Bill To
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Bill To:", 15, 65);
    doc.setFont("helvetica", "normal");
    doc.text(customer?.name || booking.customer || 'Valued Customer', 15, 71);
    if (customer?.email || booking.email) doc.text(customer?.email || booking.email, 15, 76);
    if (customer?.phone || booking.phone) doc.text(customer?.phone || booking.phone, 15, 81);
    doc.text(`Place of Supply: ${customer?.location || 'State Code 00'}`, 15, 86);

    // --- Table ---
    autoTable(doc, {
        startY: 95,
        head: [['S.No', 'Description', 'HSN/SAC', 'Taxable Val', 'GST (5%)', 'Total']],
        body: [[
            '1',
            `Booking Ref: ${booking.title}`,
            '9985',
            (booking.amount / 1.05).toFixed(2),
            (booking.amount - (booking.amount / 1.05)).toFixed(2),
            booking.amount.toLocaleString('en-IN')
        ]],
        foot: [[
            '', 'Total', '', '', '', `INR ${booking.amount.toLocaleString('en-IN')}`
        ]],
        theme: 'grid',
        headStyles: { fillColor: [88, 28, 135], textColor: 255 },
        footStyles: { fillColor: [243, 244, 246], textColor: 0, fontStyle: 'bold' }
    });

    // --- Bank Details ---
    // @ts-ignore
    let yPos = doc.lastAutoTable.finalY + 15;

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Bank Details:", 15, yPos);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    yPos += 6;
    doc.text(`Account Name: ${company.bank.accountName}`, 15, yPos);
    doc.text(`Bank Name: ${company.bank.name}`, 15, yPos + 5);
    doc.text(`Account Number: ${company.bank.accountNo}`, 15, yPos + 10);
    doc.text(`IFSC Code: ${company.bank.ifsc}`, 15, yPos + 15);

    // --- Footer ---
    doc.save(`Invoice_${booking.invoiceNo || booking.id}.pdf`);
};
